# Generated by Django 3.0 on 2021-03-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0002_auto_20210325_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='edo',
            field=models.CharField(blank=True, choices=[('Nuevo', 'Nuevo'), ('Usado', 'Usado')], max_length=1000),
        ),
    ]
