# Generated by Django 3.0 on 2021-03-26 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0003_auto_20210325_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='image',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='InmuebleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='images/')),
                ('inmueble', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inmuebles.Inmueble')),
            ],
        ),
    ]
