# Generated by Django 2.2 on 2021-04-01 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0009_auto_20210328_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('subtitle', models.CharField(max_length=300)),
                ('img', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('desc', models.CharField(max_length=300)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('img', models.CharField(max_length=500)),
                ('details', models.CharField(max_length=500)),
                ('detailsTitle', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='image',
            field=models.FileField(blank=True, upload_to='here/2021/04/01'),
        ),
        migrations.AlterField(
            model_name='inmuebleimage',
            name='images',
            field=models.FileField(upload_to='here/images/2021/04/01'),
        ),
    ]
