# Generated by Django 2.2 on 2021-04-01 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0010_auto_20210401_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='img',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
