# Generated by Django 2.2 on 2021-04-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0012_auto_20210402_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='details',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
