# Generated by Django 2.2 on 2021-04-02 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0013_post_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='posting',
            field=models.CharField(blank=True, choices=[('Casa', 'Casa'), ('Apartamento', 'Apartamento'), ('Lote', 'Lote'), ('Oficina', 'Oficina')], max_length=1000),
        ),
    ]
