# Generated by Django 2.2 on 2021-04-02 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0014_inmueble_posting'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='enlace',
            field=models.URLField(blank=True, choices=[('Casa', 'Casa'), ('Apartamento', 'Apartamento'), ('Lote', 'Lote'), ('Oficina', 'Oficina')], max_length=128),
        ),
    ]
