# Generated by Django 2.2 on 2021-04-02 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0015_inmueble_enlace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmueble',
            name='enlace',
        ),
    ]
