# Generated by Django 2.2 on 2021-04-12 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0018_auto_20210404_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='proposito',
            field=models.CharField(blank=True, choices=[('Venta', 'Venta'), ('Alquiler', 'Alquiler')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='image',
            field=models.FileField(blank=True, upload_to='here/2021/04/12'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Casa', 'Casa'), ('Apartamento', 'Apartamento'), ('Townhouse', 'Townhouse'), ('Lote', 'Lote'), ('Oficina', 'Oficina'), ('Comercial', 'Comercial')], default='Error', max_length=50),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='ubicacion',
            field=models.CharField(blank=True, choices=[('Ciudad Ojeda', 'Ciudad Ojeda'), ('Tamare', 'Tamare'), ('Tía Juana', 'Tía Juana'), ('Lagunillas', 'Lagunillas'), ('Maracaibo', 'Maracaibo'), ('Cabimas', 'Cabimas')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='inmuebleimage',
            name='images',
            field=models.FileField(upload_to='here/images/2021/04/12'),
        ),
    ]
