# Generated by Django 2.2 on 2021-04-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebles', '0019_auto_20210412_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='message',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='image',
            field=models.FileField(blank=True, upload_to='here/2021/04/19'),
        ),
        migrations.AlterField(
            model_name='inmuebleimage',
            name='images',
            field=models.FileField(upload_to='here/images/2021/04/19'),
        ),
    ]
